name: sonat_animation_templates
description: Hjelpe-komponenter og templates for fagdag i Sonat.
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
